---
title: "My title"
subtitle: "My subtitle if needed"
author: 
  - Colin Sihan Yang
  - Lexun Yu
  - Siddharth Gowda
thanks: "Code and data are available at: [https://github.com/yulexun/projecthammer](https://github.com/yulexun/projecthammer)."
date: today
date-format: long
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(palmerpenguins)
library(arrow)
library(gridExtra)
library(ggplot2)
```


# Introduction

Egg prices have fluctuated in recent years due to various economic and environmental factors [@bundale_why_2023]. In Canada, egg pricing and marketing are regulated by the government. According to @ministry_of_agriculture_food_and_agribusiness_and_ministry_of_rural_affairs_supply_2023, the Canadian Hatching Egg Producers (CHEP) determines annual national production levels for hatching eggs with input from an advisory committee composed of industry and government representatives. These numbers are then allocated to provinces and adjusted throughout the year to meet demand. However, as @filipp_project_2024 noted, research on Canadian grocery food prices remains limited. 

This paper examines the factors influencing egg prices in Canada. This approach aims to identify areas that could explain recent price trends, providing a foundation for future studies on the Canadian egg market.

[Results paragraph]

The remainder of this paper is structured as follows: @sec-data provides an overview of the data. We then present our results in @sec-result and discuss the implications, limitations, and future research directions in @sec-discussion.

The data gathering and analysis is done in R [@citeR] with the following packages: knitr [@knitr], tidyverse [@tidyverse], ggplot2 [@ggplot2], dplyr [@dplyr], arrow [@arrow], here [@here] and lubridate [@lubridate].

# Data {#sec-data}
## Measurement
The raw data is obtained in SQLite form from @filipp_project_2024's website named Project Hammer. The raw dataset contains two tables. The first table contains various product, product names, and the vendor of the products. The second table contains old and current price, as well as price per unit.

## Cleaning

We clean the data with the clean_data.sql script and the exploratory_data_analysis R script. We retrieve data related to "White Eggs" and "Brown Eggs" from two tables, `raw` and `product`, with the following steps:

- Selects various columns including `nowtime`, `vendor`, `product_id`, `product_name`, `brand`, `current_price`, `old_price`, `units`, and `other`.
- Converts `price_per_unit` to a numeric format, stripping out symbols (like `$` and `/item`) and renaming it as `price_per_unit_numeric`.
- Joins `raw` and `product` tables on `product_id`.
- Filters for products containing "White Eggs" or "Brown Eggs" in their names and ensures `price_per_unit` is not `NULL`.


\newpage


# References


